# from .TimeActivityAnalysis import TimeActivityAnalysisWidget
from .InterestingActivityAnalysis import InterestingActivityAnalysisWidget
from .FriendsActivityAnalysis import FriendsActivityAnalysisWidget